workflows:
  build-android:
    name: Build Global Markets APK
    max_build_duration: 30
    instance_type: mac_pro
    environment:
      groups:
        - keystore_credentials   # puoi lasciare vuoto se usi la firma di test
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    scripts:
      - name: Set up environment
        script: |
          echo "Using Java version:"
          java -version
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
