workflows:
  android-apk:
    name: Build Global Markets APK
    max_build_duration: 30
    environment:
      android:
        image: default
      java: 17
    scripts:
      - name: Clean Project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - claudio.carati.pc@gmail.com
