workflows:
  build-android:
    name: Build Global Markets APK
    max_build_duration: 30
    environment:
      flutter: stable  # anche per progetti non flutter, serve per attivare ambiente Android
    scripts:
      - name: Clean Project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
