workflows:
  build-android:
    name: Build APK (Global Markets Tracker)
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: gradle assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
